SELECT CLIENTES.NOMBRE, LIBROS.TITULO, PEDIDOS.ID_PEDIDO, PEDIDOS.FECHA
FROM CLIENTES
INNER JOIN LIBROS
ON CLIENTES.ID_CLIENTE = LIBROS.ID_LIBRO
INNER JOIN PEDIDOS
ON CLIENTES.ID_CLIENTE = PEDIDOS.ID_CLIENTE
WHERE CLIENTES.NOMBRE SIMILAR TO 'Fe%|Ma%a|e|i|o|u';